permalink:    /:year/:month/:day/:title/
paginate:     10
images:       /images
name: Functional Feline Society
title: Functional Feline Society
description: Functional Feline Society's adventures in code.
url: http://Functional-Feline-Society.github.io
plugins:
  - jekyll-feed